### PR TITLE
Add fibromyalgia map

### PR DESCRIPTION
**Pull request by willsvankumc**
Adding fibromyalgia map to imagemap module at the request of a medical researcher at the University of Kansas.

### CODE REVIEW

**Comment by willsvankumc** [comment]
@pbchase @ChemiKyle 
Thank you for the guidance on https://github.com/ctsit/imagemap/pull/46
I have taken this over and believe I have made the necessary changes.

**Comment by ChemiKyle** [comment]
Hi @willsvankumc, I've made a couple changes to fix conflicts caused by your PR being based of off the `master` branch (we use the [git-flow model](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) so additions are made from the `develop` branch and PRs should target it). I made a [PR on your repo](https://github.com/willsvankumc/imagemap/pull/1) since I can't push directly to it.

Unfortunately that won't be the end of it, there's a mismatch between your coordinates in `fibromyalgia.html` and the image itself that you'll also need to fix:

image

**Comment by willsvankumc** [comment]
@ChemiKyle thanks so much for the feedback, I merged the rebase, and uploaded new coordinates that are *hopefully* correct. I used a different tool this time (native apple coordinate map with preview)

**Comment by ChemiKyle** [comment]
@willsvankumc you've over-corrected a bit on some, though chest/breast is about right now
image  
I'm not sure what your testing environment is, but after saving an updated `maps/fibromyalgia.html` file you can just reload the DataEntry page and the clickable regions will update.

I'd suggest increasing the size of the selections to meet the edges of the selection boxes.

One last note is that you're welcome to credit yourself and your colleague in the `README.md` for adding this map to the module on the same line that you list the copyright for the image itself.

___
Regarding testing environment, if you don't have a local one already, we use [redcap-docker-compose](https://github.com/123andy/redcap-docker-compose). We wrote a guide to setting up [module development using that environment](https://ctsit.github.io/redcap_external_module_development_guide/) as well.

**Comment by willsvankumc** [comment]
@ChemiKyle my apologies, the photo viewer I was using my coordinate tool on decided to scale down the image, explains small/wrong boxes. Should be good this time, thank you for the docker repo as well.

**Comment by ChemiKyle** [comment]
@willsvankumc third time does not appear to be the charm, there's still a scaling issue:

image

I'd recommend using https://imagemap.org/ or https://www.image-map.net/ to generate your html

**Comment by willsvankumc** [comment]
I ended up updating them using https://imagemap.org/ as well, would you like to commit my update or should I commit mine? @ChemiKyle 

My test environment is setup and works quite well with 
```
<!-- AMAbody -->
 <area target="" data-key="1" title="Right jaw" href="" shape="rect" coords="353,137,377,162">
 <area target="" data-key="2" title="Left jaw" href="" shape="rect" coords="733,140,757,162">
 <area target="" data-key="3" title="Neck" href="" shape="rect" coords="505,190,529,213">
 <area target="" data-key="4" title="Right shoulder" href="" shape="rect" coords="259,231,287,257">
 <area target="" data-key="5" title="Left shoulder" href="" shape="rect" coords="698,245,724,268">
 <area target="" data-key="6" title="Chest or breast" href="" shape="rect" coords="342,266,368,293">
 <area target="" data-key="7" title="Upper back" href="" shape="rect" coords="811,265,838,292">
 <area target="" data-key="8" title="Right upper arm" href="" shape="rect" coords="197,349,221,372">
 <area target="" data-key="9" title="Left upper arm" href="" shape="rect" coords="677,344,705,371">
 <area target="" data-key="10" title="Abdomen" href="" shape="rect" coords="380,407,408,432">
 <area target="" data-key="11" title="Lower back" href="" shape="rect" coords="807,443,834,469">
 <area target="" data-key="12" title="Right lower arm" href="" shape="rect" coords="144,448,171,474">
 <area target="" data-key="13" title="Left lower arm" href="" shape="rect" coords="625,464,648,489">
 <area target="" data-key="14" title="Right hip or buttocks" href="" shape="rect" coords="260,542,287,570">
 <area target="" data-key="15" title="Left hip or buttocks" href="" shape="rect" coords="714,542,742,570">
 <area target="" data-key="16" title="Right upper leg" href="" shape="rect" coords="282,676,307,703">
 <area target="" data-key="17" title="Left upper leg" href="" shape="rect" coords="720,674,749,702">
 <area target="" data-key="18" title="Right lower leg" href="" shape="rect" coords="228,888,257,915">
 <area target="" data-key="19" title="Left lower leg" href="" shape="rect" coords="736,885,764,912">
```

**Comment by ChemiKyle** [comment]
@willsvankumc mine were made with a macro so they're all the same size; I vote for machine precision. Once you merge my PR and we can finally merge this one.

**Comment by willsvankumc** [comment]
ah thanks again. Merged your coordinates in @ChemiKyle

**Pull request merged**
