### PR TITLE
Adding body maps with selectable grids of size 10 pixels x 10 pixels

### PR DESCRIPTION
**Pull request by schatto1**
Hi!

A study here at University of Utah wanted to use the Image Map module, but with granular selectable areas on a body map (front and back). This is currently in use with a production project and we have a version 1.11.1 running on our server- wanted to see if we can merge this upstream so we don't have to maintain our custom Image Map module in the filesystem.

Would be happy to make any changes if required!

Our team previously inquired about this in the forum: https://redcap.vumc.org/community/post.php?id=206492. This would be step 7!

### CODE REVIEW

**Comment by davwillev** [comment]
This would be a very useful addition to the module for other users

**Comment by pbchase** [comment]
@schatto1, could you update the README.md to describe your new imagemap? Could you do it in the style in which the other imagemaps are already documented? I.e., add these things:

- A section that describes the image map, shows the images, and shows the keys and values for the image map. Give your image map a _name_. At the moment it looks you're calling it "GRIDS" or "Grids Body Map", or maybe "Grids for CTSI7245". Pick a name and run with that. The section should also say why your image map is special. This module already has multiple body maps, but yours must be special for some reason. Tell us why it is special. I'm sure you know that reason better than us, so we'd like you to write that. 
- An entry [Usage](https://github.com/ctsit/imagemap?tab=readme-ov-file#usage) section that tells us what action tag will invoke your imagemap
- An entry in the [Acknowledgements & Copyright](https://github.com/ctsit/imagemap?tab=readme-ov-file#acknowledgements--copyright) section that acknowledges the creator of the image map and any copyright holder(s). It seems likely there is some investigator that wants their work acknowledged.

**Comment by schatto1** [comment]
Thanks @pbchase - will work on that right away!

**Comment by saipavan10-git** [comment]
Hi @schatto1 ,

I’ve attached a zip file with an example instrument crafted with the grid body image maps. This example serves as a guide to demonstrate the application of the new imagemaps. You are welcome to modify and adapt it as needed. You can add this example instrument to the documentation folder within this repository at [docs](https://github.com/ctsit/imagemap/tree/cdb193428d8d9ba3432dc35eaf6215082130d2a8/docs). 

[grids_body_maps_Instrument Example.zip](https://github.com/ctsit/imagemap/files/15489591/grids_body_maps_Instrument.Example.zip)

**Comment by schatto1** [comment]
Hi @pbchase and @saipavan10-git,

Thanks so much for your patience. I just pushed the following:
- README containing an updated name and description of the image map, an entry in the Usage section, and an entry in the Acknowledgements & Copyright section
- config.json that has the updated name and description of the image map
- Instrument example zip file that has all the image maps, including the fields for the grid body image maps created by @saipavan10-git 
- example_project XML file that has all the image maps, including the fields for the grid body image maps created by @saipavan10-git 

Please let me know if there's anything else that needs be modified, thanks!

**Comment by saipavan10-git** [comment]
LGTM. Tested the imagemaps using the example instrument. It works as expected.

**Review by saipavan10-git — APPROVED** [review]

**Comment by schatto1** [comment]
Thank you!

**Pull request merged**
