### PR TITLE
DO-Touch.NET body image map

### PR DESCRIPTION
**Pull request by frgeof**
We are adding the DO-Touch.NET body images and maps (in colour and grey format) for use by the community. Also, adding documentation about DO-Touch.NET body image maps and fixing grammatical typos in the readme.md and documentation.php files.

### CODE REVIEW

**Comment by marlycormar** [comment]
Hi @frgeof, thank you for improving the documentation!

For future references, please do PRs against the develop branch. Some notes:
- The fragment `docs/Instrument\ Example.zip` is not a typo; the backslash means that there is a space between `Instrument` and `Example`. If the backslash is removed, the corresponding link on the README.md will not work.
- The name of the images didn't match (`DO-Touch.NET-Body_colour.png` on the `config.json` vs. `img/DO-Touch_NET-Body_colour.png`). Do not worry about fixing this; I will address it.
- The map `do_touch_net_body_grey.html` is not correct (note that the images `do_touch_net_body_grey.png` and `do_touch_net_body_colour.png` have different sizes but their corresponding map files are the same). Please upload a new `do_touch_net_body_grey.html` map with the correct regions.

Thanks!

**Comment by frgeof** [comment]
Whoops, I'm so sorry about that! I must have pulled the wrong local file for the .png. :blush: The .NET vs _NET was a hack to fix a conflict with the .js files. (An issue which took me much longer to locate than I want to admit.) I'll be right back with better code. 😁

**Comment by marlycormar** [comment]
Thank you @frgeof. The new image aligns well with the mapping you previously provided.

**Comment by ChemiKyle** [comment]
Hi @frgeof,

I have tested merged @marlycormar's PR, #40 which includes your contributions and her file name adjustments. I will close this PR as it's redundant.

Thank you again for contributing!

**Comment by marlycormar** [comment]
Hi @frgeof, v1.4.3 of the Imagemap Module is now available in the [REDCap Repository of External Modules](https://redcap.vanderbilt.edu/consortium/modules/index.php). It includes the DO-Touch.NET image maps you provided.

**Pull request closed without merging**
